postgres:
  image: postgres
  ports:
    - 5432:5432
  volumes:
    - postgres-data:/var/lib/postgresql/data
  environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=password

pgadmin:
  image: dpage/pgadmin4
  ports:
    - 8080:80
  volumes:
    - pgadmin-data:/var/lib/pgadmin
  environment:
    - PGADMIN_DEFAULT_EMAIL=charlesfauman@gmail.com
    - PGADMIN_DEFAULT_PASSWORD=secret
    - PGADMIN_LISTEN_PORT=80
